# Build on dev environment:
on:
  pull_request:
    branches:
      - dev
env:
  REPO: helm
  TAGS: v0.0.1

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        find . -name "requirements.txt" -type f -exec pip install -r {} \;        

    - name: Run tests
      run: |
        echo "Running tests"
        find . -name "test_*.py" -type f -exec pytest {} \;

  build_and_push:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: build code
      run: |
       echo "building"
       docker build -t=${DOCKERHUB_USERNAME}/${DOCKERHUB_PASSWORD}:${TAGS} .
      
    - name: Run when push is merged
      if: github.ref_type == 'branch' && github.ref == 'refs/heads/dev'
      run: |
       echo "Trigger Ok!"
