# Build on dev environment:
on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install -r ./app/requirements.txt

    - name: Run tests
      run: |
        echo "Running tests"
        pytest ./app/test_main.py

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: build code
      run: |
       echo "building"
       docker build -t=app .
      
    - name: Run when push is merged
      if: github.ref_type == 'branch' && github.ref == 'refs/heads/dev'
      run: |
       echo "Trigger Ok!"
